### ISSUE TITLE
1. User Story: Homepage with Featured Mini-Games

### ISSUE THREAD

**Issue by tomMckechnie-90** [tomMckechnie-90/RETROPLAY#2]
As a user,
I want to visit the homepage and play a retro mini-game,
so that I can start having fun and enjoy the retro feel.

**Acceptance Criteria:**

- [x] 	The homepage loads within 3 seconds.
- [x] 	The user can access the featured mini-games by clicking the link on the homepage.
- [x] #12
- [x] 	A clear and visible "Start Playing" button for each game.

**Tasks:**

- [x] Design a simple homepage layout.
- [x] Include bootstrap cards for each game.
- [x] Add a call-to-action button or instruction to start playing.
