### ISSUE TITLE
2. User Story: Games Pages

### ISSUE THREAD

**Issue by tomMckechnie-90** [tomMckechnie-90/RETROPLAY#3]
As a user,
I want to access a page with a dedicated retro game,
so that I can enjoy the game I have chosen without any unnecessary distractions.

**Acceptance Criteria:**

- [ ] The games page displays the dedicated retro game and a brief description.
- [ ] Each game has a "Play Now" button that starts the chosen game.
- [ ] The page is simple, with no clutter, and easy to navigate.

**Tasks:**

- [ ] Create a simple game with easy controls and with descriptions.
- [ ] Choose and code games for each page.
- [ ] Ensure the layout is clean and mobile-responsive.
